version: '3.1'

services:
  backend:
    image: 860319243069.dkr.ecr.us-east-2.amazonaws.com/marvel-backend:latest
    ports:
      - 3000:3000
    networks:
      - public

  frontend:
    image: 860319243069.dkr.ecr.us-east-2.amazonaws.com/marvel-frontend:latest
    ports:
      - 8080:80
    networks:
      - public

networks:
  public:

