version: '3.1'

services:
  backend:
    image: 860319243069.dkr.ecr.us-east-2.amazonaws.com/marvel:latest
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./server:/app
    networks:
      - public

  frontend:
    image: 860319243069.dkr.ecr.us-east-2.amazonaws.com/marvel:latest
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
    networks:
      - public

networks:
  public:

