version: '3.1'

services:
  backend:
    build:
      context: ./
      dockerfile: docker/Dockerfile
      target: dev
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./server:/app

  frontend:
    build:
      context: ./
      dockerfile: docker/Dockerfile
      target: dev
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app

