version: '3.1'

services:
  backend:
    build: ./docker
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./server:/app
    networks:
      - public

  frontend:
    build: ./docker
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
    networks:
      - public

networks:
  public:

